# Generated by Django 5.2.3 on 2025-07-10 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_date_booking_purpose_alter_booking_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('room', 'date', 'start_time', 'end_time'), name='unique_room_booking'),
        ),
    ]
