# Generated by Django 5.2.3 on 2025-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_unique_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
