# Generated by Django 5.2.3 on 2025-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_room_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
